#!/bin/bash
set -eu

service acpid restart

cat <<EOD
For first time audio support, you may wish to run:

  sudo skylake-audio-helper get-topology
  sudo skylake-audio-helper reset

Then reboot.
EOD
exit 0
